# Generated by Django 3.2.5 on 2021-07-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20210710_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Известная женщина', 'verbose_name_plural': 'Известные женщины'},
        ),
    ]
